In [1]:
from load_data import ImageLoader
from feature_extractors import SURFExtractor, HOGExtractor
from vector_quantizer import VectorQuantizer
import os

In [2]:
loader = ImageLoader('fashion-data')
train_data = loader.get_train_data()

partial test data loaded from numpy file
partial train data loaded from numpy file


In [5]:
if os.path.isfile(os.path.join('fashion-data', 'surf-features.npy')):
    print('loading SURF features for training data from numpy file')
    surf_features = loader.load_data('surf-features.npy')
else:
    print('extracting SURF features for training data')
    surf_features = SURFExtractor(train_data, 400).get_features()
    loader.store_data(surf_features, 'surf-features.npy')

loading SURF features for training data from numpy file


In [3]:
if os.path.isfile(os.path.join('fashion-data', 'hog-features.npy')):
    print('loading HOG features for training data from numpy file')
    hog_features = loader.load_data('hog-features.npy')
else:
    print('extracting HOG features for training data')
    hog_features = HOGExtractor(train_data).get_features()
    loader.store_data(surf_features, 'hog-features.npy')

extracting HOG features for training data
(116964,)


IndexError: tuple index out of range

In [13]:
from scipy.cluster import vq

In [24]:
whitened = vq.whiten(surf_features)

In [25]:
(codebook, _) = vq.kmeans(whitened, 128)

In [23]:
encoded_features = vq.vq(whitened, codebook)

In [28]:
hog_features

[array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0